# Generated by Django 2.2.2 on 2019-07-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190702_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='pub_date',
            new_name='timestamp',
        ),
    ]
