# Generated by Django 2.2.2 on 2019-06-29 21:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='default.png', verbose_name='course image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(verbose_name='course slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title of the course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(verbose_name='course position in the section'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Section', verbose_name='section to which belongs the course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(verbose_name='lesson slug'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='thumbnail of the course video'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=120, verbose_name='lesson title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(max_length=200, verbose_name='link to the video of the course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course', verbose_name='course section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.IntegerField(verbose_name='section number'),
        ),
    ]
