# Generated by Django 2.2.2 on 2019-07-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190701_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='course is free ?'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True, verbose_name='priceof the course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Section', verbose_name='lesson belongs to'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course', verbose_name='section belongs to'),
        ),
    ]
