# Generated by Django 2.2.2 on 2019-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190701_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True, verbose_name='price of the course'),
        ),
    ]
