# Generated by Django 2.2.2 on 2019-07-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190701_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='technology name')),
                ('title', models.CharField(max_length=120, verbose_name='title of the tech')),
                ('slug', models.SlugField(verbose_name='tech slug')),
                ('image', models.ImageField(default='default.png', upload_to='', verbose_name='tech image')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='technology',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Technology', verbose_name='belongs to'),
        ),
    ]
