# Generated by Django 2.2.2 on 2019-07-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190703_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Technology', verbose_name='belongs to'),
        ),
    ]
