# Generated by Django 2.2.2 on 2019-07-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190703_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='name',
        ),
    ]
