# Generated by Django 2.2.2 on 2019-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_technology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='position',
            field=models.IntegerField(default=None, verbose_name='course number'),
            preserve_default=False,
        ),
    ]
