# Generated by Django 2.2.2 on 2019-07-03 09:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title of the section'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
    ]
